### PR TITLE
fix: update factory impl

### PR DESCRIPTION
**Pull request by kulkarohan**
verified here: https://goerli.basescan.org/address/0xf0fd838913e9407edac7e51629de21eaf748b50a#code

### CODE REVIEW

**Comment by iainnash** [comment]
Can we verify the impl of the 721 drop?

https://goerli.basescan.org/address/0x824dd1ccd0824a15913b454a7e5d3bf0c6b2beed#code

**Comment by kulkarohan** [comment]
addresses updated and verified here:

https://goerli.basescan.org/address/0x421B6ad0CdD20bE3636F3511B6ae244d8F668dB1

https://goerli.basescan.org/address/0x0ABdD5AA61E9107519DB7cD626442B905284B7eb

**Comment by oveddan** [comment]
would be cool, when the fork test is merged, to add to the fork test the check that this is configured correctly

**Comment by iainnash** [comment]
yes planning to do that :)

**Review by iainnash — APPROVED** [review]

**Pull request merged**
